kakao:
  client-id: 2874c74d0b5306bd4c7cf2485f045577
  redirect-uri: http://localhost:8080/login

pw-role:
  password-rejex: ^(?=.*[a-zA-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,16}$
  
naver:
  request-token-uri: http://nid.naver.com/oauth2.0/token
  client-id: 89sNuCel1ctNo5pSU3bR
  client-secret: O4Bof6cwVl
  redirect-uri: http://localhost:8080/api/naver/callback
  
coolsms:
  api:
    key: NCS53PZHXZGQTIMZ
    secret: OZJQ52BWLKR8SKHBRUEPGZWY70ROXHKO
    form_number: 01086176289